In [2]:
print("Hello, World!")

Hello, World!

In [3]:
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

print("Successfully authenticated!")

Successfully authenticated!

In [ ]:
# Data Exploration

In [2]:
#importing libraries
import pandas as pd

In [ ]:
print(pd.__version__)

3.0.2

In [ ]:
df = pd.read_csv('Walmart.csv', encoding_errors='ignore')

df.shape

(10051, 11)

In [ ]:
df.head

<bound method NDFrame.head of        invoice_id   Branch         City                category unit_price  \
0               1  WALM003  San Antonio       Health and beauty     $74.69
1               2  WALM048    Harlingen  Electronic accessories     $15.28
2               3  WALM067  Haltom City      Home and lifestyle     $46.33
3               4  WALM064      Bedford       Health and beauty     $58.22
4               5  WALM013       Irving       Sports and travel     $86.31
...           ...      ...          ...                     ...        ...
10046        9996  WALM056      Rowlett     Fashion accessories        $37
10047        9997  WALM030   Richardson      Home and lifestyle        $58
10048        9998  WALM050     Victoria     Fashion accessories        $52
10049        9999  WALM032        Tyler      Home and lifestyle        $79
10050       10000  WALM069     Rockwall     Fashion accessories        $62

       quantity      date      time payment_method  rating  profit_margin
0           7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1           5.0  08/03/19  10:29:00           Cash     9.6           0.48
2           7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3           8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4           7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...         ...       ...       ...            ...     ...            ...
10046       3.0  03/08/23  10:10:00           Cash     3.0           0.33
10047       2.0  22/02/21  14:20:00           Cash     7.0           0.48
10048       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
10049       2.0  25/02/21  12:25:00           Cash     7.0           0.48
10050       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[10051 rows x 11 columns]>

In [ ]:
df.describe()
#quantity column has a count of 10020, but all other columns have a count of 10051, which means there are 31 missing values in quantity column.

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [ ]:
df.info()
#unit_price and quantity columns have 31 missing values, which confirms the observation from describe() that there are 31 missing values in quantity column.
#unit_price column is a string object, which may need to be converted to a numeric data type for analysis.

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [ ]:
df.duplicated().sum()
#duplicated().sum() checks for duplicate rows in the dataset. In this case, there are 51 duplicate rows in the dataset.

np.int64(51)

In [ ]:
df.drop_duplicates(inplace=True)
#drop_duplicates() removes duplicate rows from the dataset.
df.duplicated().sum()
#after dropping duplicates, there are 0 duplicate rows in the dataset. this will help ensure that our analysis is not skewed by duplicate entries, but also affect the entire dataset.

np.int64(0)

In [ ]:
df.shape

(9969, 11)

In [14]:
df.isnull().sum()
#isnull().sum() checks for missing values in each column of the dataset. In this dataset, there are 31 null values in both the unit_price and quantity columns, while all other columns have 0 null values.

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [ ]:
#dropping duplicates did not affect the number of missing values in the dataset.
#For this project we will drop rows with missing values in the interest of time, but we could and probably should explore other options for handling missing data, such as imputation or using algorithms that can handle missing values.
df.dropna(inplace=True)
#dropna() removes rows with missing values from the dataset.

In [18]:
df.isnull().sum()
#double-checking that missing values have been removed. there are now 0 null values in the dataset, which means all rows with missing values have been dropped.
df.shape
#after dropping rows with missing values, the dataset has 9969 rows and 11 columns

(9969, 11)

In [20]:
#recall that unit_price column is a string, which will need to be converted to a numeric data type for analysis.
df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)
#this code removes the dollar sign from the unit_price column and converts the values to float data.

In [ ]:
df.head()
#double-checking that values in unit_price column no longer have dollar signs.

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [20]:
df.info()
#double-checking that unit_price column is now a float data type.

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

In [21]:
#adding a total column to the dataset by multiplying unit_price and quantity columns together.
df['total'] = df['unit_price'] * df['quantity']
#this code creates a new column called total by multiplying the unit_price and quantity columns together. this will allow us to analyze total sales for each transaction.

In [22]:
df.head()
#double-checking that total column has been added to the dataset and contains the correct values.

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [ ]:
#took a few days off so I had to re-import the libraries and re-run the prior code to get back to this point in the analysis.
import pandas as pd

In [6]:
df = pd.read_csv('Walmart.csv', encoding_errors='ignore')

In [1]:
#mysql connection

import pymysql
from sqlalchemy import create_engine

In [ ]:
df.to_csv('walmart_clean.csv', index=False)
#saving cleaned dataset to a new csv file named walmart_clean.csv.

In [24]:
#writing cleaned dataset to mysql database using pandas to_sql function. if_exists='append' will add the data to the existing table if it already exists, and index=False prevents pandas from writing row indices to the database.
df.to_sql(name='walmart', con=engine_mysql, if_exists='append', index=False)

9969

In [25]:
df.shape

(9969, 12)